import React from "react";
import "./globals.css";
import Navbar from "@/components/commons/Navbar/Navbar";
import { Roboto } from "next/font/google"
export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};
const roboto = Roboto({ subsets: ["latin"], weight: ["100", "300", "400", "500", "700", "900"] });

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang="en">
         <body className={`container mx-auto px-2 ${roboto.className}`}>
            <Navbar />
            {children}
         </body>
      </html>
   );
}
